export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const PLAYER_PROFILE = 'PLAYER_PROFILE';

export const GAME_TYPE_SELECTED = 'GAME_TYPE_SELECTED';

export const GAME_STATE_WAITING = 'GAME_STATE_WAITING';
export const GAME_STATE_PLAYING = 'GAME_STATE_PLAYING';
export const GAME_STATE_CLOSED = 'GAME_STATE_CLOSED';
export const PLAYER_COLLECTION = 'PLAYER_COLLECTION';

export const UPDATE_PLAYER_LIST = 'UPDATE_PLAYER_LIST';
export const UPDATE_GAME_STATE= 'UPDATE_GAME_STATE';
export const UPDATE_GAME_ACTION= 'UPDATE_GAME_ACTION';
export const NEXT_ROUND = 'NEXT_ROUND';
export const UPDATE_CHAT_MESSAGE = 'UPDATE_CHAT_MESSAGE';

export const GAME_ACTION_TAKE = "T";
export const GAME_ACTION_GET = "G";